### ISSUE TITLE
Leftovers and documentation... 

### ISSUE THREAD

**Issue by BKeyport** [Tom-Hirschberger/MMM-ValuesByNotification#14]
Just a couple of notes: 

1) Line 47 "compass: false, // If user requests, convert values to compass direction, for weather stations and the like."  can be deleted as you didn't use my compass logic, opting for the more flexible (and better) transformers. 

2) You didn't document "unitSpace: false, // If user requests, add a space for units. " I noticed it's still working. :)

**Comment by Tom-Hirschberger** [comment]
Hi and thank you for your feedback.
I added the missing option to documentation and removed "compass" now.
