### ISSUE TITLE
Suggestion: Invalid Data Colorization

### ISSUE THREAD

**Issue by BKeyport** [Tom-Hirschberger/MMM-ValuesByNotification#16]
As an enhancement to reuseCount, can we have a configuration option to indicate that data is old? 

Basically, I want my data to turn a color other than basic when it's reused by resuseCount.

Thanks again, Tom.

**Comment by Tom-Hirschberger** [comment]
Hi,

should not be a big deal to add this feature.
I am on vacation at the moment and do not have access to my development environment but I will check for it when I am home.

**Comment by Tom-Hirschberger** [comment]
Hi,

i am back home from my trip and just released version 0.1.0 of the module.
The module now adds classes to the elements if a reused value is used. The class can be configured by a new config option "reusedClass" which has the value "reused" in default.

A simple CSS like:
```CSS
.MMM-ValuesByNotification .reused {
  color: orange;
}
```

will do the trick.

**Comment by Tom-Hirschberger** [comment]
As i updated a dependency with this release please make sure to run `npm install` during the update.

**Comment by BKeyport** [comment]
Seems to be working with one note - Found out that the base MagicMirror *must* be current for it to work with the dependency update. If it's even one edition out, it'll fail.

**Comment by BKeyport** [comment]
I take that back, something's not working. CommandtoNotification is retrieving info, but everything is stuck at the "NA" Value.

**Comment by Tom-Hirschberger** [comment]
Hi,

that's bad news.
The MagicMirror installation itself should not be affected.
You need to go to the module directory and do a `npm install` in the directory.
Is this what you did?

The `npm install` in the MagicMirror directory only is needed if you update MagicMirror itself and does NOT install any module dependencies. 

Are there any errors in the log files and in the Web development view?

**Comment by Tom-Hirschberger** [comment]
Hi,

that's bad news.
The MagicMirror installation itself should not be affected.
You need to go to the module directory and do a `npm install` in the directory.
Is this what you did?

The `npm install` in the MagicMirror directory only is needed if you update MagicMirror itself.

Are there any errors in the log files and in the Web development view?

I will check for older versions I only tested with the current one.

**Comment by BKeyport** [comment]
As for the MM install - it blank screened a mirror I don't keep up on (my mom's unit). Once I updated the main install, it works. Might just be an oddity. No errors anywhere other than the standard GUI warnings (MESA-LOADER). 

Once I updated mom's mirror, it came back, but both my mirrors are reporting N/A values rather than actual results from the notification. 

I did the NPM Install in your directory as usual (as a force of habit, even on modules that claim to be clean, I run npm install). 

Everything else is working - the system does turn orange if it thinks it's returning used data.

**Comment by Tom-Hirschberger** [comment]
Can provide your module config and a piece of sample data to me?

I will need to setup a different development environment to check this out.

Both my mirrors work well with the new version. But my systems are fully updated and I use one of the latest node 16 versions.

**Comment by BKeyport** [comment]
My MagicMirrors are installed using Sam's Script, PM2 based. Updates are using Sam's Scripts. Unit this config came from was updated today. (I have backed down your module to the previous version, and it works, using "git checkout HEAD~1" )



Module Config: 

```
               {
                        module: "MMM-CommandToNotification", // https://github.com/Tom-Hirschberger/MMM-CommandToNotification
                        disabled: false,
                        config: {
                                updateInterval: 30,
                                sync: false,
                                commands: [
                                        {
                                                script: "/usr/bin/curl",
                                                args: "-X GET -H 'application/json' http://192.168.0.6:80/v1/current_conditions",
                                                timeout: 5000,
                                                sync: false,
                                                notifications: [
                                                        "WeatherLink",
                                                ],
                                        },

                                ],
                        },
                },
```

Sample Data: 

```
{"data":{"did":"001D0A71573B","ts":1693209080,"conditions":[{"lsid":434637,"data_structure_type":1,"txid":1,"temp": 61.6,"hum":87.3,"dew_point": 57.8,"wet_bulb": 59.1,"heat_index": 62.2,"wind_chill": 61.6,"thw_index": 62.2,"thsw_index":null,"wind_speed_last":4.00,"wind_dir_last":218,"wind_speed_avg_last_1_min":1.06,"wind_dir_scalar_avg_last_1_min":222,"wind_speed_avg_last_2_min":1.31,"wind_dir_scalar_avg_last_2_min":205,"wind_speed_hi_last_2_min":3.00,"wind_dir_at_hi_speed_last_2_min":180,"wind_speed_avg_last_10_min":0.81,"wind_dir_scalar_avg_last_10_min":159,"wind_speed_hi_last_10_min":3.00,"wind_dir_at_hi_speed_last_10_min":116,"rain_size":1,"rain_rate_last":0,"rain_rate_hi":0,"rainfall_last_15_min":0,"rain_rate_hi_last_15_min":0,"rainfall_last_60_min":0,"rainfall_last_24_hr":0,"rain_storm":0,"rain_storm_start_at":null,"solar_rad":null,"uv_index":null,"rx_state":0,"trans_battery_flag":0,"rainfall_daily":0,"rainfall_monthly":34,"rainfall_year":2828,"rain_storm_last":7,"rain_storm_last_start_at":1692978480,"rain_storm_last_end_at":1693072860},{"lsid":434634,"data_structure_type":4,"temp_in": 86.9,"hum_in":36.3,"dew_point_in": 57.0,"heat_index_in": 86.2},{"lsid":434633,"data_structure_type":3,"bar_sea_level":30.113,"bar_trend": 0.033,"bar_absolute":29.649}]},"error":null}
```

**Comment by BKeyport** [comment]
Whoops, forgot the right config.  Excuse the formatting oddity, that's due to having to copy and paste twice. 

```
               {
                        module: "MMM-ValuesByNotification", // https://github.com/Tom-Hirschberger/MMM-ValuesByNotification
                        position: "top_bar",
                        config: {
                                animationSpeed: 0,
                                updateInterval: 15,
                                reuseCount: 10,
                                groups: [
                                        {
                                                items: [
                                                        {
                                                                notification: "WeatherLink",
                                                                values: [
                                                                        {
                                                                                valueTitle: "Temperature",
                                                                                valueUnit: "°",
                                                                                jsonpath: "data.conditions[0].temp",
                                                                        },
                                                                        {
                                                                                valueTitle: "Wind Speed",
                                                                                valueUnit: "MPH",
                                                                                jsonpath: "data.conditions[0].wind_speed_last",
                                                                                unitSpace: true,
                                                                        },
                                                                        {
                                                                                valueTitle: "Humidity",
                                                                                valueUnit: "%",
                                                                                jsonpath: "data.conditions[0].hum",
                                                                        },
  {
                                                                                valueTitle: "Wind Direction",
                                                                                jsonpath: "data.conditions[0].wind_dir_last",
                                                                        },
                                                                ]
                                                        },
                                                ]
                                        },
                                ]
                        },
```

**Comment by Tom-Hirschberger** [comment]
Perfect. I use Sam's script, too.

I will check for the problem in the next hours.
If it is related to the dependency update I will revert to the old one. Only did the update as performance increased up to 30 percent with the new version.

**Comment by Tom-Hirschberger** [comment]
You had been right. The new version of jsonpath-plus only worked with the current MagicMirror version.
I reverted the changes, fixed another unrelated bug and releases version 0.1.1 a few minutes ago.

**Comment by BKeyport** [comment]
Reverting the dependency and the other fixes took care of all issues. It's working perfectly now..
