### ISSUE TITLE
Different values of reuseCount in different groups

### ISSUE THREAD

**Issue by hildwin** [Tom-Hirschberger/MMM-ValuesByNotification#22]
Hi, thank you very much for your incredible work. 
How can I define reuseCount differently in different groups? I tried it this way, but it seems not working. 

 ```
		{
			module: "MMM-ValuesByNotification",
			disabled: false, 
			position: "top_right",
			header: "Informationen",
			config: {
			 groups: [
			  {
			   groupIcon: "fa fa-car",	
			   valueFormat: "\"${value}\".replace(\"ON\",\"Tor zu\").replace(\"OFF\",\"Tor auf\")",
			   reuseCount: 10080,
			   items: [
				{
					notification: "GPTOR",
					valueTitle: "Passat",
					values: [
					 {},
					]
				},
				{
					notification: "GATOR",
					valueTitle: "Audi",
					values: [
					 {},
					]
				},
			   ]
			  },
			  {
				// group2
				groupTitle: "Power",
				groupIcon: "fa fa-plug",
				reuseCount: 60,
				items: [
					{
						notification: "POWER",
						unitSpace: true,
						values: [
						 {
						   valueUnit: "W",
						 },
						]
					   },
				],
			  },
			 ]
			},
		   },	  
 ```
After a few minutes the values of GATOR und GPTOR change to "na".

**Comment by Tom-Hirschberger** [comment]
Hi,

i only had implemented to set the `reuseCount` on item level but i released a new version a couple of seconds ago.
It should be possible, now

**Comment by hildwin** [comment]
Thanks again! 
[General options](https://github.com/Tom-Hirschberger/MMM-ValuesByNotification?tab=readme-ov-file#general-options) gave me the impression that it also works on group level.

**Comment by Tom-Hirschberger** [comment]
Your welcome.

You are right. The docs did not correspond with the code in this point.
