### ISSUE TITLE
Suggestion: two groups side by side in one module

### ISSUE THREAD

**Issue by hildwin** [Tom-Hirschberger/MMM-ValuesByNotification#24]
I'd like to show two groups side by side in one module. The examples show just one group below the other. 
Is this already possible? For example with a special css code?

**Comment by Tom-Hirschberger** [comment]
Hi, this should be possible with CSS.
The module uses flexbox layout for ordering the elements.

I found this guide very helpful: https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by hildwin** [comment]
I'll look into it.
